version: '3.4'

services:
  userservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDatabaseSettings__ConnectionString=mongodb://root:example@mongo:27017
      - ConnectionStrings__UserSqlDbConnectionString=Server=sql;Database=usersdb;User Id=sa;Password=123asdQ!
    ports:
      - "656:80"
      - "748:443"
    depends_on:
      - mongo
      - sql
  sql:
    image: microsoft/mssql-server-linux:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123asdQ!
    ports:
      - "5433:1433"  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: UserEvents
    ports:
      - 27017:27017

  mongo.express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo